### ISSUE TITLE
Make sure gulp 3.9+ is used

### ISSUE THREAD

**Issue by airatdev** [fs/react-base#4]
If gulp version is old enough (prior to 3.9.0 gulp [didn't have babel support](https://github.com/gulpjs/gulp/blob/master/CHANGELOG.md#390)) this boilerplate will fail to start with `No gulpfile found` error. This should be either checked [here](https://github.com/fs/react-base/blob/master/bin/setup#L4) or mentioned in README.

/cc @maratfakhreev

**Comment by maratfakhreev** [comment]
@airatshigapov Thank you for the comment, it will be fixed in the near future

**Comment by maratfakhreev** [comment]
#6 a bit of work

**Comment by maratfakhreev** [comment]
Fixed by #6
